In [1]:
import pandas as pd
import numpy as np

In [2]:
from zipfile import ZipFile

In [3]:
def gen_store_ts_feat():
    z = ZipFile('./data/train.zip','r')
    df_train = pd.read_csv(z.open('train.csv'))
    df_train = df_train[df_train.Open!=0]
    y = df_train
    df_train = df_train[['Store','DayOfWeek','Date','Promo','StateHoliday','SchoolHoliday','Sales']]
    return df_train

In [17]:
def gen_store_feat(log=True):
    df_store = pd.read_csv('./data/store.csv')
    if log:
        df_store.CompetitionDistance.fillna(df_store.CompetitionDistance.mean(),inplace=True)
        df_store.loc[:,'CompetitionDistance'] = df_store.loc[:,'CompetitionDistance'].map(lambda n:int(np.log(n)))
    df_store.loc[:,'CompetitionOpenSinceMonth'] = df_store.CompetitionOpenSinceMonth.map(np.isnan)
    df_store = df_store[['Store','StoreType','Assortment','CompetitionDistance','CompetitionOpenSinceMonth','Promo2']]
    return df_store

In [18]:
def get_X_y(df_train,df_store):
    df = pd.merge(df_train,df_store,on='Store',how='outer')
    y = df.Sales
    df = df[[c for c in df.columns if c!='Sales']]
    df = df.applymap(str)
    dv = DictVectorizer()
    X = dv.fit_transform(df.to_dict('records'))
    return X,y

In [19]:
df_store

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,Promo2
0,1,c,a,7,False,0
1,2,a,a,6,False,1
2,3,a,a,9,False,1
3,4,c,c,6,False,0
4,5,a,a,10,False,0
5,6,a,a,5,False,0
6,7,a,c,10,False,0
7,8,a,a,8,False,0
8,9,a,c,7,False,0
9,10,a,a,8,False,0
10,11,a,c,6,False,1
11,12,a,c,6,True,1
12,13,d,a,5,True,1
13,14,a,a,7,False,1
14,15,d,c,8,False,1
15,16,a,c,8,True,0
16,17,a,a,3,False,1
17,18,d,c,9,False,1
18,19,a,c,8,True,1
19,20,d,a,7,False,1
20,21,c,c,6,False,1
21,22,a,a,6,True,1
22,23,d,a,8,False,0
23,24,a,c,8,False,1
24,25,c,a,6,False,0
25,26,d,a,7,True,0
26,27,a,a,4,False,1
27,28,a,a,7,False,1
28,29,d,c,7,True,0
29,30,a,a,3,False,1
...,...,...,...,...,...,...
1085,1086,a,a,5,False,1
1086,1087,d,c,7,False,0
1087,1088,a,a,8,False,1
1088,1089,d,a,8,False,0
1089,1090,a,a,5,True,1
1090,1091,a,c,9,True,0
1091,1092,a,a,5,False,1
1092,1093,c,c,9,False,0
1093,1094,d,a,7,False,1
1094,1095,a,a,6,False,1
1095,1096,a,c,7,True,1
1096,1097,b,b,6,False,0
1097,1098,a,a,7,False,0
1098,1099,a,c,5,False,1
1099,1100,a,a,6,True,1
1100,1101,d,c,8,False,0
1101,1102,a,a,6,False,1
1102,1103,d,c,7,False,1
1103,1104,d,a,5,False,1
1104,1105,c,c,5,False,1
1105,1106,a,c,8,False,1
1106,1107,a,a,7,False,1
1107,1108,a,a,6,False,0
1108,1109,c,a,8,False,1
1109,1110,c,c,6,False,0
1110,1111,a,a,7,False,1
1111,1112,c,c,7,False,0
1112,1113,a,c,9,True,0
1113,1114,a,c,6,True,0
1114,1115,d,c,8,True,1

In [20]:
df = pd.merge(df_train,df_store,on='Store',how='outer')

In [24]:
y = df.Sales

In [28]:
df = df[[c for c in df.columns if c!='Sales']]

In [31]:
df = df.applymap(str)

In [32]:
from sklearn.feature_extraction import DictVectorizer

In [33]:
dv = DictVectorizer()

In [35]:
df

,Store,DayOfWeek,Date,Promo,StateHoliday,SchoolHoliday,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,Promo2
0,1,5,2015-07-31,1,0,1,c,a,7,False,0
1,1,4,2015-07-30,1,0,1,c,a,7,False,0
2,1,3,2015-07-29,1,0,1,c,a,7,False,0
3,1,2,2015-07-28,1,0,1,c,a,7,False,0
4,1,1,2015-07-27,1,0,1,c,a,7,False,0
5,1,6,2015-07-25,0,0,0,c,a,7,False,0
6,1,5,2015-07-24,0,0,0,c,a,7,False,0
7,1,4,2015-07-23,0,0,0,c,a,7,False,0
8,1,3,2015-07-22,0,0,0,c,a,7,False,0
9,1,2,2015-07-21,0,0,0,c,a,7,False,0
10,1,1,2015-07-20,0,0,0,c,a,7,False,0
11,1,6,2015-07-18,0,0,0,c,a,7,False,0
12,1,5,2015-07-17,1,0,0,c,a,7,False,0
13,1,4,2015-07-16,1,0,0,c,a,7,False,0
14,1,3,2015-07-15,1,0,0,c,a,7,False,0
15,1,2,2015-07-14,1,0,0,c,a,7,False,0
16,1,1,2015-07-13,1,0,0,c,a,7,False,0
17,1,6,2015-07-11,0,0,0,c,a,7,False,0
18,1,5,2015-07-10,0,0,0,c,a,7,False,0
19,1,4,2015-07-09,0,0,0,c,a,7,False,0
20,1,3,2015-07-08,0,0,0,c,a,7,False,0
21,1,2,2015-07-07,0,0,0,c,a,7,False,0
22,1,1,2015-07-06,0,0,0,c,a,7,False,0
23,1,6,2015-07-04,0,0,0,c,a,7,False,0
24,1,5,2015-07-03,1,0,0,c,a,7,False,0
25,1,4,2015-07-02,1,0,0,c,a,7,False,0
26,1,3,2015-07-01,1,0,0,c,a,7,False,0
27,1,2,2015-06-30,1,0,0,c,a,7,False,0
28,1,1,2015-06-29,1,0,0,c,a,7,False,0
29,1,6,2015-06-27,0,0,0,c,a,7,False,0
...,...,...,...,...,...,...,...,...,...,...,...
844362,292,2,2013-02-05,1,0,1,a,a,7,False,0
844363,292,1,2013-02-04,1,0,1,a,a,7,False,0
844364,292,6,2013-02-02,0,0,0,a,a,7,False,0
844365,292,5,2013-02-01,0,0,0,a,a,7,False,0
844366,292,4,2013-01-31,0,0,0,a,a,7,False,0
844367,292,3,2013-01-30,0,0,0,a,a,7,False,0
844368,292,2,2013-01-29,0,0,0,a,a,7,False,0
844369,292,1,2013-01-28,0,0,0,a,a,7,False,0
844370,292,6,2013-01-26,0,0,0,a,a,7,False,0
844371,292,5,2013-01-25,1,0,0,a,a,7,False,0
844372,292,4,2013-01-24,1,0,0,a,a,7,False,0
844373,292,3,2013-01-23,1,0,0,a,a,7,False,0
844374,292,2,2013-01-22,1,0,0,a,a,7,False,0
844375,292,1,2013-01-21,1,0,0,a,a,7,False,0
844376,292,6,2013-01-19,0,0,0,a,a,7,False,0
844377,292,5,2013-01-18,0,0,0,a,a,7,False,0
844378,292,4,2013-01-17,0,0,0,a,a,7,False,0
844379,292,3,2013-01-16,0,0,0,a,a,7,False,0
844380,292,2,2013-01-15,0,0,0,a,a,7,False,0
844381,292,1,2013-01-14,0,0,0,a,a,7,False,0
844382,292,6,2013-01-12,0,0,0,a,a,7,False,0
844383,292,5,2013-01-11,1,0,0,a,a,7,False,0
844384,292,4,2013-01-10,1,0,0,a,a,7,False,0
844385,292,3,2013-01-09,1,0,0,a,a,7,False,0
844386,292,2,2013-01-08,1,0,0,a,a,7,False,0
844387,292,1,2013-01-07,1,0,0,a,a,7,False,0
844388,292,6,2013-01-05,0,0,0,a,a,7,False,0
844389,292,5,2013-01-04,0,0,1,a,a,7,False,0
844390,292,4,2013-01-03,0,0,1,a,a,7,False,0
844391,292,3,2013-01-02,0,0,1,a,a,7,False,0

In [34]:
X = dv.fit_transform(df.to_dict('records'))

MemoryError: bad allocation

In [36]:
def get_X_y(df_train,df_store):
    df = pd.merge(df_train,df_store,on='Store',how='outer')
    y = df.Sales
    df = df[[c for c in df.columns if c!='Sales']]
    df = df.applymap(str)
    dv = DictVectorizer()
    X = dv.fit_transform(df.to_dict('records'))
    return X,y